# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grant < Formula
  desc "A tool consumes SBOMS and details license information"
  homepage "https://github.com/anchore/grant"
  version "0.6.7"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anchore/grant/releases/download/v0.6.7/grant_0.6.7_darwin_amd64.tar.gz"
      sha256 "dfe32f40209248ac2c60c3bb2afe811902f1e65020a0e6337d83de88ba58fc91"

      define_method(:install) do
        bin.install "grant"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anchore/grant/releases/download/v0.6.7/grant_0.6.7_darwin_arm64.tar.gz"
      sha256 "411932c4770c52dcbbf6c6da0cac54afc67a21406c3d682b8226cbb49ea82cb0"

      define_method(:install) do
        bin.install "grant"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anchore/grant/releases/download/v0.6.7/grant_0.6.7_linux_amd64.tar.gz"
      sha256 "66572af8d363b87f010195215d90649effa94f26a6e9ef7d181a7874a3959560"
      define_method(:install) do
        bin.install "grant"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anchore/grant/releases/download/v0.6.7/grant_0.6.7_linux_arm64.tar.gz"
      sha256 "3df2fa5eb42c22f739d7dd17ac267979619d7b82718b231307bbfa4acd3bf44e"
      define_method(:install) do
        bin.install "grant"
      end
    end
  end
end
