# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grant < Formula
  desc "A tool consumes SBOMS and details license information"
  homepage "https://github.com/anchore/grant"
  version "0.6.8"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anchore/grant/releases/download/v0.6.8/grant_0.6.8_darwin_amd64.tar.gz"
      sha256 "e8b2b3b3666ef4bb3731d0399485215258f8c205ab30f1557b9b51b34b8bd44c"

      define_method(:install) do
        bin.install "grant"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anchore/grant/releases/download/v0.6.8/grant_0.6.8_darwin_arm64.tar.gz"
      sha256 "3d8f315f4f27d9efc8fc712ee27f10cd0df64ac794226580ea5346234f2d6806"

      define_method(:install) do
        bin.install "grant"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anchore/grant/releases/download/v0.6.8/grant_0.6.8_linux_amd64.tar.gz"
      sha256 "6500f8bbf0f20fb993de8084686e199f0ba1eb494769ff75454286d5ef63f919"
      define_method(:install) do
        bin.install "grant"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anchore/grant/releases/download/v0.6.8/grant_0.6.8_linux_arm64.tar.gz"
      sha256 "15ec0b4346a64b5580958dc62c4e7c25ca9e59b7582bab9706679f6b9d2288b8"
      define_method(:install) do
        bin.install "grant"
      end
    end
  end
end
