# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grant < Formula
  desc "A tool consumes SBOMS and details license information"
  homepage "https://github.com/anchore/grant"
  version "0.3.1"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/anchore/grant/releases/download/v0.3.1/grant_0.3.1_darwin_amd64.tar.gz"
      sha256 "2433f54b38cd4efdf27e31e736045117bb281c28a2651fd3c0c5e9edfe75f671"

      def install
        bin.install "grant"
      end
    end
    on_arm do
      url "https://github.com/anchore/grant/releases/download/v0.3.1/grant_0.3.1_darwin_arm64.tar.gz"
      sha256 "062c7b183cedf468413ee4146a1b67b94f115d8ee8b7cbc8bf6f6cce5a862a1a"

      def install
        bin.install "grant"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anchore/grant/releases/download/v0.3.1/grant_0.3.1_linux_amd64.tar.gz"
        sha256 "bc6a9356e6317b8ea0ad528a64ce5ebf194bcbb20f7c79002840acf85bc9edf4"

        def install
          bin.install "grant"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anchore/grant/releases/download/v0.3.1/grant_0.3.1_linux_arm64.tar.gz"
        sha256 "79c8e029565a0a627e7333323d650355c9fb4791268523f3f473868ee885122a"

        def install
          bin.install "grant"
        end
      end
    end
  end
end
